### ISSUE TITLE
Create a number guessing program using any programming langauge

### ISSUE THREAD

**Issue by harsh-dart** [harsh-dart/HactoberFest2024#1]
Task is to create a number guessing program using any programming langauge. User has to guess which number is choosen by the program in given attempts.

**Comment by farhan-sayeed** [comment]
@sharayuanuse did your PR count in Hacktober PR?

**Comment by sharayuanuse** [comment]
@farhan-sayeed Not yet. The PR is currently under the 6 day review period.
