### ISSUE TITLE
 Add Binary Search Implementation 

### ISSUE THREAD

**Issue by Madhuj275** [harsh-dart/HactoberFest2024#18]
## Description
I would like to propose an issue to add a comprehensive implementation of the Binary Search algorithm in our codebase. This implementation should include clear input parameters, constraints, and output specifications, along with sample test cases to demonstrate its functionality.

### Requirements
1. **Code Implementation**: Implement the Binary Search algorithm in [specify programming language, e.g., Python, Java, C++].
2. **Input**:
   - A sorted array of integers.
   - An integer target value to search for.
3. **Constraints**:
   - The array should be sorted in ascending order.
   - The length of the array should be between 1 and 1000.
   - The target value can be any integer within the range of the array values.
4. **Output**:
   - Return the index of the target value if found; otherwise, return -1.

### Sample Test Case
```plaintext
Input: 
Array: [1, 2, 3, 4, 5]
Target: 3

Output: 
Index: 2
```

Feel free to modify any part of this template to better fit your project or preferences!

**Comment by shrutikamahale** [comment]
Hi @Madhuj275 , can you add label as hactoberfest/ hactoberfest-accepted and assign this to me?

**Comment by harsh-dart** [comment]
Hi @Madhuj275, Do you want to work on this issue or should I assign it to @shrutikamahale.

**Comment by harsh-dart** [comment]
Assigning this issue to @shrutikamahale

**Comment by Madhuj275** [comment]
I have the proper implementation of issue
